version: "3.9"
services:
  postgres1:
    image: postgres:14.5
    shm_size: 128mb
    env_file:
      - ./docker/db/config/library.env
    volumes:
      - ./docker/db/scripts/library.sql:/docker-entrypoint-initdb.d/library.sql
      - ./dz/postgres1:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  postgres2:
    image: postgres:14.5
    shm_size: 128mb
    env_file:
      - ./docker/db/config/2.env
    volumes:
      - ./docker/db/scripts/2.sql:/docker-entrypoint-initdb.d/idk2.sql
      - ./dz/postgres2:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  postgres3:
    image: postgres:14.5
    shm_size: 128mb
    env_file:
      - ./docker/db/config/3.env
    volumes:
      - ./docker/db/scripts/3.sql:/docker-entrypoint-initdb.d/idk3.sql
      - ./dz/postgres3:/var/lib/postgresql/data
    ports:
      - "5434:5432"
